import fs from "node:fs";
import { writeJson } from "./common.ts";

const baseline = JSON.parse(fs.readFileSync("output/baseline/summary.json", "utf8"));
const faultTolerant = JSON.parse(fs.readFileSync("output/fault_tolerant/summary.json", "utf8"));
const percent = (value: number) => `${(value * 100).toFixed(2)}%`;

const rows = [
  ["Successful transactions", baseline.successful_transactions, faultTolerant.successful_transactions,
    `+${faultTolerant.successful_transactions - baseline.successful_transactions}`],
  ["Failed transactions", baseline.transactions_lost, faultTolerant.transactions_lost,
    `-${baseline.transactions_lost - faultTolerant.transactions_lost}`],
  ["Lost amount (KZT)", baseline.lost_amount_kzt, faultTolerant.lost_amount_kzt,
    `-${baseline.lost_amount_kzt - faultTolerant.lost_amount_kzt}`],
  ["Retries", baseline.retries, faultTolerant.retries, `+${faultTolerant.retries}`],
  ["Rollbacks", baseline.rollbacks, faultTolerant.rollbacks, `+${faultTolerant.rollbacks}`],
  ["Completion rate", percent(baseline.completion_rate), percent(faultTolerant.completion_rate),
    `+${((faultTolerant.completion_rate - baseline.completion_rate) * 100).toFixed(2)} pp`],
];

const calculations = {
  recovery_improvement_pp: Number(((faultTolerant.completion_rate - baseline.completion_rate) * 100).toFixed(2)),
  recovery_improvement_factor: faultTolerant.successful_transactions / baseline.successful_transactions,
  transaction_loss_reduction: Number(((baseline.transactions_lost - faultTolerant.transactions_lost) / baseline.transactions_lost).toFixed(4)),
  amount_loss_reduction: Number(((baseline.lost_amount_kzt - faultTolerant.lost_amount_kzt) / baseline.lost_amount_kzt).toFixed(4)),
};

const markdown = [
  "# Part E - Before/After comparison (generated by src/compare.ts)", "",
  "| Metric | Baseline | Fault-tolerant | Improvement |", "|---|---|---|---|",
  ...rows.map((row) => `| ${row.join(" | ")} |`), "",
  `* Recovery improvement = ${percent(faultTolerant.completion_rate)} - ${percent(baseline.completion_rate)} = **${calculations.recovery_improvement_pp} pp** (${faultTolerant.successful_transactions}/${baseline.successful_transactions} = ${calculations.recovery_improvement_factor}x more successful transactions)`,
  `* Transaction-loss reduction = (${baseline.transactions_lost} - ${faultTolerant.transactions_lost}) / ${baseline.transactions_lost} = **${percent(calculations.transaction_loss_reduction)}**`,
  `* Amount-loss reduction = (${baseline.lost_amount_kzt} - ${faultTolerant.lost_amount_kzt}) / ${baseline.lost_amount_kzt} = **${percent(calculations.amount_loss_reduction)}**`,
];
fs.writeFileSync("output/comparison.md", markdown.join("\n") + "\n");
writeJson("output/comparison.json", { table: rows, calculations });
console.log(markdown.join("\n"));
